### ISSUE TITLE
How to get the value on selecting a date from datepicker.

### ISSUE THREAD

**Issue by adeel-sohail** [AvroraTeam/DatePickerX#3]
Hello i am using this incredible datepicker and want to point to a function and get the selected value on clicking on a date. So that i can know which date is selected and then i can go to my function for validation and other stuff. 

Also i have tried the focus out on input but it is not returning current date, rather it is returning previous date. 

Any kind of help would be much appreciated.

**Comment by LukaszMoskala** [comment]
A little bit late, but you can try using `onChange`, like so:
```
<input type='text' onChange='myFunction(this)' size='10'>
```
and then, in javascript:
```
function myFunction(handle) {
  alert(handle.value);
}
```
It's almost a year since you posted this question, but maybe someone else will find it usefull

**Comment by AlexKrupko** [comment]
Hi @adeel3612 ,

Sorry for the so later response. 

You can listen the `change` event on your input element and just get the DatePickerX value inside event handler. Something like this - 
```javascript
var element = document.querySelector('input');
element.DatePickerX.init();
element.addEventListener('change', function()
{
    var value = this.DatePickerX.getValue();
});
```
