### ISSUE TITLE
Show months and years only, hide days.

### ISSUE THREAD

**Issue by stanislavhosek** [AvroraTeam/DatePickerX#5]
Hello, good work! It is possible to hide/turn off days in calendar? I need only months and years. Thank you for answer.

**Comment by AlexKrupko** [comment]
Hi @stanislavhosek, 

Unfortunately, we don't have such feature now.

**Comment by hug0b** [comment]
Why is there hard coded examples with only months and years in the demo then ? Seems misleading.

**Comment by AlexKrupko** [comment]
Thanks @hug0b ! The demo has been updated.
